// Auto-generated by dev/viva-2026/exam-app/build_practice_data.py — do not edit by hand.
// Term names and example questions only (no answers). 'band' is for the
// random draw mix and is never shown to students.
const VIVA_PRACTICE_DATA = {
  "terms": [
    {
      "term": "Artificial Intelligence (AI)",
      "band": "E"
    },
    {
      "term": "Machine Learning (ML)",
      "band": "E"
    },
    {
      "term": "Generalisation",
      "band": "E"
    },
    {
      "term": "Prompt Engineering",
      "band": "E"
    },
    {
      "term": "Context Engineering",
      "band": "M"
    },
    {
      "term": "LLM Problem-Solving Loop",
      "band": "M"
    },
    {
      "term": "Overfitting",
      "band": "E"
    },
    {
      "term": "Underfitting",
      "band": "E"
    },
    {
      "term": "Bias-Variance Tradeoff",
      "band": "H"
    },
    {
      "term": "Cross-Validation",
      "band": "M"
    },
    {
      "term": "Linear Regression",
      "band": "E"
    },
    {
      "term": "Regularisation",
      "band": "M"
    },
    {
      "term": "Lasso Regression (L1)",
      "band": "H"
    },
    {
      "term": "Mean Absolute Error (MAE)",
      "band": "E"
    },
    {
      "term": "Classification",
      "band": "E"
    },
    {
      "term": "Decision Tree",
      "band": "E"
    },
    {
      "term": "Random Forest",
      "band": "M"
    },
    {
      "term": "Confusion Matrix",
      "band": "E"
    },
    {
      "term": "ROC Curve / AUC (Receiver Operating Characteristic / Area Under the Curve)",
      "band": "H"
    },
    {
      "term": "Ensemble Learning",
      "band": "M"
    },
    {
      "term": "Feature Importance",
      "band": "M"
    },
    {
      "term": "Classification Threshold",
      "band": "M"
    },
    {
      "term": "Clustering",
      "band": "E"
    },
    {
      "term": "K-Means",
      "band": "M"
    },
    {
      "term": "Principal Component Analysis (PCA)",
      "band": "M"
    },
    {
      "term": "Hyperparameter",
      "band": "H"
    },
    {
      "term": "Cluster Stability",
      "band": "H"
    },
    {
      "term": "Silhouette Score",
      "band": "M"
    },
    {
      "term": "Neural Network (Artificial)",
      "band": "M"
    },
    {
      "term": "Perceptron",
      "band": "M"
    },
    {
      "term": "Activation Function",
      "band": "M"
    },
    {
      "term": "Backpropagation",
      "band": "H"
    },
    {
      "term": "Dropout",
      "band": "M"
    },
    {
      "term": "Training Loop (Epoch and Batch)",
      "band": "H"
    },
    {
      "term": "Loss Function",
      "band": "M"
    },
    {
      "term": "Convolutional Neural Network (CNN)",
      "band": "M"
    },
    {
      "term": "Transformer",
      "band": "H"
    },
    {
      "term": "Embedding",
      "band": "M"
    },
    {
      "term": "Self-Attention",
      "band": "H"
    },
    {
      "term": "Hallucination (LLM)",
      "band": "M"
    }
  ],
  "questions": [
    {
      "method": "Regression",
      "question": "A researcher wants to predict DASS Depression scores from Big Five personality traits in a large student sample. Which ML regression approach would you use, and how would you check it's trustworthy?",
      "band": "E"
    },
    {
      "method": "Regression",
      "question": "You have 60 self-report items and only 250 participants, and you want to predict perceived stress. Should you use Ridge or Lasso, and why?",
      "band": "M"
    },
    {
      "method": "Regression",
      "question": "A colleague reports R² = 0.85 predicting wellbeing from lifestyle variables in their training data, but the model performs poorly on a new cohort. What's gone wrong, and what would you do differently?",
      "band": "H"
    },
    {
      "method": "Classification",
      "question": "A university counselling service wants to flag students likely to be experiencing elevated depression (PHQ-9 ≥ 5) from a short survey. Which ML classification approach would you use, and which metric matters most?",
      "band": "E"
    },
    {
      "method": "Classification",
      "question": "Your classifier detects a rare clinical condition (~8% prevalence) and hits 92% accuracy. Why might you be more cautious than your supervisor?",
      "band": "M"
    },
    {
      "method": "Dimensionality Reduction",
      "question": "You want a 2D visualisation of participants in a high-dimensional symptom dataset to see whether clinical and non-clinical groups separate. Would you use PCA or UMAP, and why?",
      "band": "M"
    },
    {
      "method": "Neural Network",
      "question": "A colleague has 200 participants with personality questionnaire data and wants to use a deep neural network to predict wellbeing because 'deep learning is more powerful'. What would you recommend?",
      "band": "E"
    },
    {
      "method": "Embeddings/LLM",
      "question": "You have 400 interview transcripts about coping during the pandemic. How would you use embeddings to find recurring themes, and how would you check the themes are real?",
      "band": "H"
    },
    {
      "method": "LLM-Assisted Workflow",
      "question": "A colleague used ChatGPT to do a 'thematic analysis' of their interview transcripts and pasted the output straight into their results section. What concerns would you raise, and how should they have done it instead?",
      "band": "H"
    }
  ]
};
